language: node_js
node_js:
- '6'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
notifications:
  email: false

before_install:
  - npm install -g firebase-tools
  - npm install -g tslint
  - npm install -g typescript

install:
  - cd functions && npm install

before_script: 

script:
  - npm run build

after_success:
  - cd ..
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

# before_deploy:
#   - echo "ready?"

# deploy:
#   provider: firebase
#   token:
#     secure: $FIREBASE_TOKEN
#     # secure: IZKGj1Xnmdn8cEONQi01B857miVz3YqPIlPBKoy01Txa2o1Iy4XDUwVfrq1vOOBszEB4y7+Zvgc2Aykfcu8LJMNUuIBWBIHIB+VP86BVzHVYwEigibAb9Yk329FLfnZbujJt2F8j7M9G+d3bt29Q7OkPLQOxJgTzvhlJBt45zpw/EANtpO0QMyVHphGsn32Vuf9PKnH5KsCeXVtd3MWOyaT9cllCBw468DzwG/ZJitsT6Y+M31251e3NZoDqJ+hr4ivIwY0xMbB2oN/awoQGWKbGVfJMzFy4d/sR+CqT7xk5P2hsIjDcbUAdWDwqPAl12t2ZgUm2sryTkoIUz+Uy94bfsBVhSc5uAQ6Gcz57QDCTRHr7B+jRV6I5/rdCnoTVIu/QttyoJt+zhnmst7NEP+HUqlhpaYKlgFKElgKhCVhNSz//QXiLGWpqzZHEnglPX+aoQH5ma7vquoRVnaYJOT8tNqKjxgdAaF2mvtvMcN7Pg8BSgvIArI2v5AbQsVLsdIi6g+KNxoxQM32YeJhpo1zgpzkSkPFCpHZKagUCPOnkiyXlgdepu5Txd5auSFPr9P2lDvEpbANM1Pe3ZgUyO0+JivUbBZJ5sdXTxUIQyCnTCEk0Egys90UaxrH/ZAgEIrN8c3sIsbUopOxv182nPm3WPrb3iKQwblM7emL+A4E=
#   message: your message

# after_deploy:
#   - echo "finish :)"
