language: node_js
node_js:
- '6'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
notifications:
  email: false
before_install:
- npm install -g firebase-tools
- cd functions
install:
- npm install
before_script: 
script:
- npm run build
after_success:
- firebase deploy --token $FIREBASE_TOKEN --non-interactive
before_deploy:
- cd ..
- echo "ready?"
deploy:
  provider: firebase
  token:
    secure: PQJFGFGTXeu5q+KQLJp1tsw6v+ZwInpUS779SgPchAkuo7t8ENtJzPoZnYPgK8yQhiwzpo1XP10Z1gWnppifBal+PyyCMkBg92MfPEbejZ4jVf3mcKv8eJ3+ssqEvmIsJ8rbo8utXeIuroDFiJuLeMRIVxG1CFgn9nLPMYcMLRoKTbqbdAGFsnTYV5jAx4nLvjzZFPxJkZ1XmX6qu5L4hFBK8+IvQUBAn1KFphzFUPstJtiuDFnHmKk8r6o+X+OLP5jwCXSjlbgmpMDxSBgSap5XY3uOJkUB8f50q/JCetmnNESt1vaLDmLen9ZDF226kvXrII+8qqUmk57n12SYAhxSiMz1tpeIgK9ldNXTOMnT/80DiMOIUIzFijFuFiArthoe0LS+X2e6RDhpjldgI9hScC1fcMxfBxfFVJsxQ4cDHdoaV/W0UZpKIuQ/yDILmsJftkFCqkpwlm8nF4x4fG9ixM3jBECHGPen68k4CbilwGl7tjqhoQexBs8aS/JFAJvgztzpoicMu34PEm/SzYH0tAzT9MiZnxXIJABdEa/ddM+5p6byCioI7IpmWHckQkn26bW+j/zO2vzCxJqi8mjRCtGhbll6xoq5ryPXCfD3uSy/6wZdV3zzCNQB+wg3+T4RaPZTAm3/zUWh8/FjiW3hoAisncyosRZrg32PQ3w=
  message: your message
after_deploy:
- echo "finish :)"
env:
  global:
    secure: IZKGj1Xnmdn8cEONQi01B857miVz3YqPIlPBKoy01Txa2o1Iy4XDUwVfrq1vOOBszEB4y7+Zvgc2Aykfcu8LJMNUuIBWBIHIB+VP86BVzHVYwEigibAb9Yk329FLfnZbujJt2F8j7M9G+d3bt29Q7OkPLQOxJgTzvhlJBt45zpw/EANtpO0QMyVHphGsn32Vuf9PKnH5KsCeXVtd3MWOyaT9cllCBw468DzwG/ZJitsT6Y+M31251e3NZoDqJ+hr4ivIwY0xMbB2oN/awoQGWKbGVfJMzFy4d/sR+CqT7xk5P2hsIjDcbUAdWDwqPAl12t2ZgUm2sryTkoIUz+Uy94bfsBVhSc5uAQ6Gcz57QDCTRHr7B+jRV6I5/rdCnoTVIu/QttyoJt+zhnmst7NEP+HUqlhpaYKlgFKElgKhCVhNSz//QXiLGWpqzZHEnglPX+aoQH5ma7vquoRVnaYJOT8tNqKjxgdAaF2mvtvMcN7Pg8BSgvIArI2v5AbQsVLsdIi6g+KNxoxQM32YeJhpo1zgpzkSkPFCpHZKagUCPOnkiyXlgdepu5Txd5auSFPr9P2lDvEpbANM1Pe3ZgUyO0+JivUbBZJ5sdXTxUIQyCnTCEk0Egys90UaxrH/ZAgEIrN8c3sIsbUopOxv182nPm3WPrb3iKQwblM7emL+A4E=
